stages:
  - build
  - deploy

build-docs:
  stage: build
  image: python:3.9
  before_script:
    - pip install -r requirements-docs.txt
  script:
    - sphinx-build -b html docs/ public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deploying GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main
