stages:
  - build
  - deploy

build-docs:
  stage: build
  image: python:3.9
  before_script:
    - pip install -r requirements.txt -r requirements-docs.txt
  script:
    - cd docs
    - make clean && make html
    - mv _build/html ../public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deploying GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main
