from typing import Optional

from picsart_sdk.api_responses import ApiResponse
from picsart_sdk.clients.base.image_base_client import ImageBaseClient
from picsart_sdk.clients.requests_models import UploadRequest
from picsart_sdk.clients.requests_models.picsart_image import PicsartImage


class UploadClient(ImageBaseClient):
    """
    Client for uploading an image.

    This client provides functionality to upload images to Picsart CDN
    using either a URL or a local file path. The file will be available at:
    `https://cdn.picsart.io/<image_id>` where <image_id> is an autogenerated ID.
    """

    @property
    def _endpoint(self):
        return "upload"

    def upload_image(
        self,
        image_url: Optional[str] = None,
        image_path: Optional[str] = None,
    ) -> ApiResponse:
        """
        Upload an image to the server.

        :param image_url: The URL of the image to upload.
        :param image_path: The local path of the image to upload.
        :return: The API response with the details about the uploaded image.
        """

        request = UploadRequest(
            image=PicsartImage(image_path=image_path, image_url=image_url)
        )
        return self.post(request=request)


class AsyncUploadClient(ImageBaseClient):
    """
    Client for uploading an image using an asynchronous HTTP client.

    This client provides functionality to upload images to Picsart CDN
    using either a URL or a local file path. The file will be available at:
    `https://cdn.picsart.io/<image_id>` where <image_id> is an autogenerated ID.
    """

    @property
    def _endpoint(self):
        return "upload"

    async def upload_image(
        self,
        image_url: Optional[str] = None,
        image_path: Optional[str] = None,
    ) -> ApiResponse:
        """
        Upload an image to the server using an asynchronous HTTP client.

        :param image_url: The URL of the image to upload.
        :param image_path: The local path of the image to upload.
        :return: The API response with the details about the uploaded image.
        """
        request = UploadRequest(
            image=PicsartImage(image_path=image_path, image_url=image_url)
        )
        return await self.async_post(request=request)
